// <auto-generated />
namespace PBL3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class QLNHv6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QLNHv6));
        
        string IMigrationMetadata.Id
        {
            get { return "202505141604125_QLNH-v6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
